backend:
  name: github
  repo: jinfengxie66/blog
  branch: master
  site_url: https://jinfengxie66.github.io/blog

media_folder: "img"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "标签", name: "tag", widget: "string" }
      - { label: "标签样式类", name: "tagClass", widget: "select", options:
            [{ label: "Python 算法", value: "tag-algo" },
             { label: "Agent", value: "tag-agent" },
             { label: "大模型", value: "tag-llm" },
             { label: "深度学习", value: "tag-dl" },
             { label: "机器学习", value: "tag-ml" },
             { label: "爬虫", value: "tag-crawl" },
             { label: "数据分析", value: "tag-da" },
             { label: "其他", value: "tag-other" }] }
      - { label: "摘要", name: "summary", widget: "text" }
      - { label: "正文", name: "body", widget: "markdown" }
